INSERT INTO PRODUCT (PRICE, CATEGORY, NAME) VALUES (100.00, 'Categoria 1', 'Produto 1');
INSERT INTO PRODUCT (PRICE, CATEGORY, NAME) VALUES (200.00, 'Categoria 2', 'Produto 2');
INSERT INTO PRODUCT (PRICE, CATEGORY, NAME) VALUES (300.00, 'Categoria 3', 'Produto 3');